# Generated by Django 5.0.3 on 2024-03-09 01:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='img/')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MaxValueValidator(10000000))])),
                ('registeredDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
